branch-defaults:
  master:
    environment: revolut-test-dev
    group_suffix: null
deploy:
  artifact: target/revolut-test-0.0.1-SNAPSHOT.jar
global:
  application_name: revolut-test
  branch: null
  default_ec2_keyname: revolut-test
  default_platform: Java 8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
